// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MoviesClient is the client API for Movies service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoviesClient interface {
	SearchMovies(ctx context.Context, in *MovieKeywordAndPage, opts ...grpc.CallOption) (*MovieSearch, error)
	GetMovieDetail(ctx context.Context, in *MovieId, opts ...grpc.CallOption) (*Movie, error)
}

type moviesClient struct {
	cc grpc.ClientConnInterface
}

func NewMoviesClient(cc grpc.ClientConnInterface) MoviesClient {
	return &moviesClient{cc}
}

func (c *moviesClient) SearchMovies(ctx context.Context, in *MovieKeywordAndPage, opts ...grpc.CallOption) (*MovieSearch, error) {
	out := new(MovieSearch)
	err := c.cc.Invoke(ctx, "/model.Movies/SearchMovies", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moviesClient) GetMovieDetail(ctx context.Context, in *MovieId, opts ...grpc.CallOption) (*Movie, error) {
	out := new(Movie)
	err := c.cc.Invoke(ctx, "/model.Movies/GetMovieDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoviesServer is the server API for Movies service.
// All implementations must embed UnimplementedMoviesServer
// for forward compatibility
type MoviesServer interface {
	SearchMovies(context.Context, *MovieKeywordAndPage) (*MovieSearch, error)
	GetMovieDetail(context.Context, *MovieId) (*Movie, error)
	mustEmbedUnimplementedMoviesServer()
}

// UnimplementedMoviesServer must be embedded to have forward compatible implementations.
type UnimplementedMoviesServer struct {
}

func (UnimplementedMoviesServer) SearchMovies(context.Context, *MovieKeywordAndPage) (*MovieSearch, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMovies not implemented")
}
func (UnimplementedMoviesServer) GetMovieDetail(context.Context, *MovieId) (*Movie, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovieDetail not implemented")
}
func (UnimplementedMoviesServer) mustEmbedUnimplementedMoviesServer() {}

// UnsafeMoviesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoviesServer will
// result in compilation errors.
type UnsafeMoviesServer interface {
	mustEmbedUnimplementedMoviesServer()
}

func RegisterMoviesServer(s grpc.ServiceRegistrar, srv MoviesServer) {
	s.RegisterService(&Movies_ServiceDesc, srv)
}

func _Movies_SearchMovies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieKeywordAndPage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServer).SearchMovies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Movies/SearchMovies",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServer).SearchMovies(ctx, req.(*MovieKeywordAndPage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Movies_GetMovieDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoviesServer).GetMovieDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.Movies/GetMovieDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoviesServer).GetMovieDetail(ctx, req.(*MovieId))
	}
	return interceptor(ctx, in, info, handler)
}

// Movies_ServiceDesc is the grpc.ServiceDesc for Movies service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Movies_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.Movies",
	HandlerType: (*MoviesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchMovies",
			Handler:    _Movies_SearchMovies_Handler,
		},
		{
			MethodName: "GetMovieDetail",
			Handler:    _Movies_GetMovieDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie.proto",
}
