// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import context "context"
import mock "github.com/stretchr/testify/mock"
import searchlog "github.com/andrefebrianto/Search-Movie-Service/searchlog"

// SearchLogCommandRepository is an autogenerated mock type for the SearchLogCommandRepository type
type SearchLogCommandRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, searchLog
func (_m *SearchLogCommandRepository) Create(ctx context.Context, searchLog *searchlog.SearchLog) error {
	ret := _m.Called(ctx, searchLog)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *searchlog.SearchLog) error); ok {
		r0 = rf(ctx, searchLog)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
