// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeMoviesServer is an autogenerated mock type for the UnsafeMoviesServer type
type UnsafeMoviesServer struct {
	mock.Mock
}

// mustEmbedUnimplementedMoviesServer provides a mock function with given fields:
func (_m *UnsafeMoviesServer) mustEmbedUnimplementedMoviesServer() {
	_m.Called()
}
